export const breedList = [{ "id": 0, "name": "affenpinscher" },
{ "id": 1, "name": "african" },
{ "id": 2, "name": "airedale" },
{ "id": 3, "name": "akita" }, { "id": 4, "name": "appenzeller" },
{ "id": 5, "name": "shepherd australian" }, { "id": 6, "name": "basenji" }, 
{ "id": 7, "name": "beagle" }, { "id": 8, "name": "bluetick" }, { "id": 9, "name": "borzoi" }, 
{ "id": 10, "name": "bouvier" }, { "id": 11, "name": "boxer" },
{ "id": 12, "name": "brabancon" }, { "id": 13, "name": "briard" },
{ "id": 14, "name": "norwegian buhund" }, { "id": 15, "name": "boston bulldog" },
{ "id": 16, "name": "english bulldog" }, { "id": 17, "name": "french bulldog" },
{ "id": 18, "name": "staffordshire bullterrier" }, { "id": 19, "name": "cairn" },
{ "id": 20, "name": "australian cattledog" }, { "id": 21, "name": "chihuahua" },
{ "id": 22, "name": "chow" }, { "id": 23, "name": "clumber" }, { "id": 24, "name": "cockapoo" },
{ "id": 25, "name": "border collie" }, { "id": 26, "name": "coonhound" },
{ "id": 27, "name": "cardigan corgi" }, { "id": 28, "name": "cotondetulear" },
{ "id": 29, "name": "dachshund" }, { "id": 30, "name": "dalmatian" },
{ "id": 31, "name": "great dane" }, { "id": 32, "name": "scottish deerhound" }, 
{ "id": 33, "name": "dhole" }, { "id": 34, "name": "dingo" }, { "id": 35, "name": "doberman" },
{ "id": 36, "name": "norwegian elkhound" }, { "id": 37, "name": "entlebucher" }, { "id": 38, "name": "eskimo" }, { "id": 39, "name": "lapphund finnish" }, { "id": 40, "name": "bichon frise" }, { "id": 41, "name": "germanshepherd" }, { "id": 42, "name": "italian greyhound" }, { "id": 43, "name": "groenendael" }, { "id": 44, "name": "havanese" }, { "id": 45, "name": "afghan hound" }, { "id": 46, "name": "basset hound" }, { "id": 47, "name": "blood hound" }, { "id": 48, "name": "english hound" }, { "id": 49, "name": "ibizan hound" }, { "id": 50, "name": "plott hound" }, { "id": 51, "name": "walker hound" }, { "id": 52, "name": "husky" }, { "id": 53, "name": "keeshond" }, { "id": 54, "name": "kelpie" }, { "id": 55, "name": "komondor" }, { "id": 56, "name": "kuvasz" }, { "id": 57, "name": "labradoodle" }, { "id": 58, "name": "labrador" }, { "id": 59, "name": "leonberg" }, { "id": 60, "name": "lhasa" }, { "id": 61, "name": "malamute" }, { "id": 62, "name": "malinois" }, { "id": 63, "name": "maltese" }, { "id": 64, "name": "bull mastiff" }, { "id": 65, "name": "english mastiff" }, { "id": 66, "name": "tibetan mastiff" }, { "id": 67, "name": "mexicanhairless" }, { "id": 68, "name": "mix" }, { "id": 69, "name": "bernese mountain" }, { "id": 70, "name": "swiss mountain" }, { "id": 71, "name": "newfoundland" }, { "id": 72, "name": "otterhound" }, { "id": 73, "name": "caucasian ovcharka" }, { "id": 74, "name": "papillon" }, { "id": 75, "name": "pekinese" }, { "id": 76, "name": "pembroke" }, { "id": 77, "name": "miniature pinscher" }, { "id": 78, "name": "pitbull" }, { "id": 79, "name": "german pointer" }, { "id": 80, "name": "germanlonghair pointer" }, { "id": 81, "name": "pomeranian" }, { "id": 82, "name": "miniature poodle" }, { "id": 83, "name": "standard poodle" }, { "id": 84, "name": "toy poodle" }, { "id": 85, "name": "pug" }, { "id": 86, "name": "puggle" }, { "id": 87, "name": "pyrenees" }, { "id": 88, "name": "redbone" }, { "id": 89, "name": "chesapeake retriever" }, { "id": 90, "name": "curly retriever" }, { "id": 91, "name": "flatcoated retriever" }, { "id": 92, "name": "golden retriever" }, { "id": 93, "name": "rhodesian ridgeback" }, { "id": 94, "name": "rottweiler" }, { "id": 95, "name": "saluki" }, { "id": 96, "name": "samoyed" }, { "id": 97, "name": "schipperke" }, { "id": 98, "name": "giant schnauzer" }, { "id": 99, "name": "miniature schnauzer" }, { "id": 100, "name": "english setter" }, { "id": 101, "name": "gordon setter" }, { "id": 102, "name": "irish setter" }, { "id": 103, "name": "english sheepdog" }, { "id": 104, "name": "shetland sheepdog" }, { "id": 105, "name": "shiba" }, { "id": 106, "name": "shihtzu" }, { "id": 107, "name": "blenheim spaniel" }, { "id": 108, "name": "brittany spaniel" }, { "id": 109, "name": "cocker spaniel" }, { "id": 110, "name": "irish spaniel" }, { "id": 111, "name": "japanese spaniel" }, { "id": 112, "name": "sussex spaniel" }, { "id": 113, "name": "welsh spaniel" }, { "id": 114, "name": "english springer" }, { "id": 115, "name": "stbernard" }, { "id": 116, "name": "american terrier" }, { "id": 117, "name": "australian terrier" }, { "id": 118, "name": "bedlington terrier" }, { "id": 119, "name": "border terrier" }, { "id": 120, "name": "dandie terrier" }, { "id": 121, "name": "fox terrier" }, { "id": 122, "name": "irish terrier" }, { "id": 123, "name": "kerryblue terrier" }, { "id": 124, "name": "lakeland terrier" }, { "id": 125, "name": "norfolk terrier" }, { "id": 126, "name": "norwich terrier" }, { "id": 127, "name": "patterdale terrier" }, { "id": 128, "name": "russell terrier" }, { "id": 129, "name": "scottish terrier" }, { "id": 130, "name": "sealyham terrier" }, { "id": 131, "name": "silky terrier" }, { "id": 132, "name": "tibetan terrier" }, { "id": 133, "name": "toy terrier" }, { "id": 134, "name": "westhighland terrier" }, { "id": 135, "name": "wheaten terrier" }, { "id": 136, "name": "yorkshire terrier" }, { "id": 137, "name": "vizsla" }, { "id": 138, "name": "spanish waterdog" }, { "id": 139, "name": "weimaraner" }, { "id": 140, "name": "whippet" },
{ "id": 141, "name": "irish wolfhound" }, { "id": 142, "name": "Indian Spitz" },
{ "id": 143, "name": "Kanni" },
{ "id": 144, "name": "Chippiparai" },
{ "id": 145, "name": "Kombai" },
{ "id": 146, "name": "Rajapalayam" },
{ "id": 147, "name": "Bully kutta" },
{ "id": 148, "name": "Mudhol Hound" },
{ "id": 149, "name": "Indian Pariah Dog" }
]

